[package]
name = "lox"
version = "0.0.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
dirs = "4.0.0"
lazy_static = "1.4.0"
rustyline = "9.1.2"
snafu = "0.7.0"
structopt = "0.3.25"

[dev-dependencies]
pretty_assertions = "1.0.0"
